// src/icons/language-map.ts
// Maps common file extensions to language IDs for Seti and vscode-icons resolvers.
// Resides strictly in src/icons/ to preserve zero-mapping purity in src/core/ (FR-Q3, INTENT 3).

export const LANGUAGE_BY_EXTENSION: Record<string, string> = {
  md: 'markdown',
  markdown: 'markdown',
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  jsx: 'javascriptreact',
  ts: 'typescript',
  tsx: 'typescriptreact',
  py: 'python',
  pyw: 'python',
  json: 'json',
  jsonc: 'jsonc',
  html: 'html',
  htm: 'html',
  css: 'css',
  scss: 'scss',
  less: 'less',
  xml: 'xml',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'toml',
  ini: 'ini',
  sh: 'shellscript',
  bash: 'shellscript',
  zsh: 'shellscript',
  ps1: 'powershell',
  bat: 'bat',
  cmd: 'bat',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  cs: 'csharp',
  java: 'java',
  go: 'go',
  rs: 'rust',
  rb: 'ruby',
  php: 'php',
  lua: 'lua',
  sql: 'sql',
  r: 'r',
  swift: 'swift',
  kt: 'kotlin',
  txt: 'plaintext',
  log: 'log',
  csv: 'csv',
  tex: 'tex',
  vue: 'vue',
  svelte: 'svelte',
};
